# Generated by Django 4.0.6 on 2024-09-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('ano', models.DateField(verbose_name='Data de Publicação')),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('ano', models.DateField(verbose_name='Data de Publicação')),
                ('imagem', models.ImageField(upload_to='media/')),
                ('disponivel', models.BooleanField(default=True)),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcervoDigital.contato')),
            ],
        ),
    ]
