# Generated by Django 4.0.6 on 2024-09-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcervoDigital', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
